### PR TITLE
Support for ControlNet SD3 [for 2 GPUs,3 and 4 GPUs]

### PR DESCRIPTION
**Pull request by mali-afridi**
Hey, **I implemented ControlNetSD3 for pipefusion legacy**. As we discussed, there is noise in output image. Can you please have a look at it? I think we need to perform communication for `control_block_sample` in xDiT/legacy/pipefuser/pipelines/pip/distri_sd3_cn.py 

To replicate this image: 
```bash
cd xDiT/legacy
```

```bash
torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 4
```

Output Image 2gpu: [4 gpu image becomes more blurry]

_pipefusion_hw_1024_sync_corrected_async_gn_sp_False_u1_w2_mb4

What Image should look like: 

sd3_cn_1024

### CODE REVIEW

**Comment by Steaunk** [comment]
`torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 4 --sync_mode full_sync`
try with `full_sync` so that we can focus on warmup_step first.

**Comment by mali-afridi** [comment]
We have this logic in your file distri_sd3cn.py (**pip_timesteps is None if full_sync**):
```
            if distri_config.mode != "full_sync":
                warmup_timesteps = timesteps[: distri_config.warmup_steps + 1]
                pip_timesteps = timesteps[distri_config.warmup_steps + 1 :]
            else:
                warmup_timesteps = timesteps
                pip_timesteps = None
```

If pip_timesteps = None as a result of passing --sync_mode full_sync, we get error:
```
    for _ in range(len(pip_timesteps)):
                   ^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```
I **commented** everywhere where `pip_timesteps` was used, here is the output: 

```
DistriSD3CNPipeline from pretrain stage 1 0.0 GB
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.26s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.38s/it]
Loading pipeline components...:  44%|████████████████████████████████████████▉                                                   | 4/9 [00:03<00:04,  1.13it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.53it/s]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.33it/s]
DistriSD3CNPipeline from pretrain stage 2 16.115048448 GB
DistriSD3CNPipeline from pretrain stage 2 16.405016576 GB
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.46it/s]
memory before prepare 19.65583616 GB
DistriSD3CNPipeline from pretrain stage 3 19.65583616 GB
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.74it/s]
memory before prepare 19.365868032 GB
DistriSD3CNPipeline from pretrain stage 3 19.365868032 GB
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:02<00:00, 11.01it/s]
results/_pipefusion_hw_1024_sync_full_sync_sp_False_u1_w2_mb4 epoch time: 2.85 sec, memory: 20.171699712 GB
save images to ./results/_pipefusion_hw_1024_sync_full_sync_sp_False_u1_w2_mb4.png
Traceback (most recent call last):
  File "/home/user/xDiT/legacy/scripts/sd3cn_example.py", line 239, in <module>
    main()
  File "/home/user/xDiT/legacy/scripts/sd3cn_example.py", line 235, in main
    output.images[0].save(f"./{case_name}.png")
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'images'
```
This None is due to the code:
```
            # if distri_config.rank == 0:
            #     latents = torch.cat(latents, dim=2)

            # else:
            return None
```

**Comment by Steaunk** [comment]
I added some reviews. You can change `pip_timesteps = None` to `pip_timesteps = []`.

**Comment by mali-afridi** [comment]
Okay, so doing that makes the same blurry image and takes same time on 2gpu,4gpu. I guess issue is in warmup

**Comment by mali-afridi** [comment]
Hey, so in the warmup steps, we have this code:

```
  self.comm_manager.isend_to_next(latents)
  if distri_config.rank != 0:
      self.comm_manager.send_to_next(
          next_encoder_hidden_states, is_extra=True
      )
```
What is the difference between `send_to_next` and `isend_to_next`? I think I should perform `isend_to_next` on `control_block_samples = next_control_block_samples` which is a list intead of tensor

**Comment by Steaunk** [comment]
> Hey, so in the warmup steps, we have this code:
> 
> ```
>   self.comm_manager.isend_to_next(latents)
>   if distri_config.rank != 0:
>       self.comm_manager.send_to_next(
>           next_encoder_hidden_states, is_extra=True
>       )
> ```
> 
> What is the difference between `send_to_next` and `isend_to_next`? I think I should perform `isend_to_next` on `control_block_samples = next_control_block_samples` which is a list instead of tensor

You can roughly consider `send_to_next` as blocking communication and `isend_to_next` as non-blocking communication. And `send_to_next` is coordinated with `recv_from_prev`, which won't store the shape and need to send/recv shape first. Thus I think you should use `send_to_next` here and you can transformer `list` to `tensor`.

**Comment by mali-afridi** [comment]
Ok I used `send_to_next` for `control_block_samples = next_control_block_samples.` It works for ` full_sync` (warmup_steps) . 
I used 
Now, I will see how to perform this communication for `pip_timesteps`.Getting some size mismatch errors in forward function of controlnet if full_sync is false.  The image generated by warmup is as follows: 
_pipefusion_hw_1024_sync_full_sync_sp_False_u1_w2_mb4

**Comment by Steaunk** [comment]
Could you update your code to this PR so that we could also have a test?

**Comment by mali-afridi** [comment]
I have updated the PR, please test it by running: 
` torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 2` 
or 
 `torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 4`
for 1 gpu, pass this: 
` torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 2 --sync_mode full_sync`
The reason why it gets stuck on gpu3 or 4 is because, length of `next_control_block_samples` becomes 2 instead of 3 when passing through `DistriSD3CNTransformer2DModel` on gpu numbers >2

**Comment by mali-afridi** [comment]
Ok, so I hard coded length of next_control_block_samples =2 for distri_config.world_size>2. **Works for 2, 3 and 4 GPU!**. we have image difference though, and your image difference also exists for legacy based sd3. 
Number of steps: 28: 
**2 GPUs:** torchrun --nproc-per-node=2 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --
output_type pil --pp_num_patch 2
_**2 Gpu Inference Time: 3.66s**_
**3 GPUs:** `torchrun --nproc-per-node=3 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 2`
**_3 Gpu Inference Time: 3.24s_**
**4 GPUs:** `torchrun --nproc-per-node=4 --master_port=29502 scripts/sd3cn_example.py --output_file results/ --output_type pil --pp_num_patch 2`
**_4 Gpu Inference Time: 3.17 s_** 

image

**Pull request merged**
